Set Heroku configurations
CodiTramuntana/decidim-pinto-app pull request #1
Opened 2021-12-17 07:48 UTC by LauraJaimeC

- Procfile with Sidekiq and migrations
- Puma configuration
- Sidekiq configuration

2021-12-17 09:34 UTC, tramuntanal requested changes
Great job @LauraJaimeC !

I've just left a couple of coments to check

2021-12-17 09:34 UTC, tramuntanal commented on config/initializers/figaro.rb
> -keys = %w(SECRET_KEY_BASE)
don't we  need a different secret-key in each environment?

2021-12-17 09:34 UTC, tramuntanal commented on spec/system/homepage_spec.rb
> -      name: "Decidim Application",
I would keep this test as is, without any modification, unless we have customizations, which is not the case

2021-12-17 11:52 UTC, LauraJaimeC commented
🎉

2022-01-10 06:56 UTC, tramuntanal approved these changes

2022-01-10 06:56 UTC, merged